### PR TITLE
use pulsectl for pulse

### LINKED ISSUE #16: Implement Pulse volume control as an API
> From https://github.com/andreasvc/cplay/issues/14#issuecomment-342459451
> 
> Pulse volume control should be implemented through a proper API instead of parsing the output of shell commands as it is implemented now. You could probably fix the display of the Pulse volume easily, but if the output of `pactl` changes it would break again.

### PR DESCRIPTION
**Pull request by xi**
fixes #16

### CODE REVIEW

**Comment by xi** [comment]
For some reason this takes up 4x as the complete rest of cplay. i think this is not worth it.

**Comment by andreasvc** [comment]
Did you mean 4x the lines of code? Or something else?

**Comment by xi** [comment]
Oh sorry, I think there are some word missing in my comment.

If I remember correctly this was 4x memory usage.

**Comment by andreasvc** [comment]
Oh good to know! That might be a good reason not to go for this. On the other hand, interfacing with a CLI utility is rather brittle...

**Pull request closed without merging**
